/**
 * Deterministic markdown renderer for `HandoffBrief`.
 *
 * Pure string-concat — no markdown library (RESEARCH §Don't Hand-Roll).
 * Two consecutive calls with the same `HandoffBrief` produce byte-identical
 * output, so this layer is completely deterministic; any non-determinism
 * is upstream in `buildBrief` (gated by `gitLogEnabled`).
 *
 * Section order, per RESEARCH Q1, is enforced here as well as in the
 * synthesizer:
 *   1. Status snapshot
 *   2. Mission
 *   3. Ticket DAG
 *   4. Recent decisions
 *   5. Files touched (with M4 v1-lossy footnote)
 *   6. Working memory (below the `---` divider — agent-authored zone)
 */

import type { HandoffBrief } from "./types.js";

const FILES_TOUCHED_FOOTNOTE =
  "> *(v1: files-touched is reconstructed from git log; uncommitted " +
  "changes and tickets without commit references are missing. " +
  "Tracked: D-02.)*";

export function renderBrief(brief: HandoffBrief): string {
  const header = renderHeader(brief);
  const top = [
    renderSection(brief.sections.statusSnapshot.heading, brief.sections.statusSnapshot.body),
    renderSection(brief.sections.mission.heading, brief.sections.mission.body),
    renderSection(brief.sections.ticketDag.heading, brief.sections.ticketDag.body),
    renderSection(brief.sections.recentDecisions.heading, brief.sections.recentDecisions.body),
    renderSection(
      brief.sections.filesTouched.heading,
      `${brief.sections.filesTouched.body}\n\n${FILES_TOUCHED_FOOTNOTE}`
    ),
  ].join("\n\n");

  const divider = "\n\n---\n\n";

  const workingMemory = renderSection(
    brief.sections.workingMemory.heading,
    brief.sections.workingMemory.body
  );

  const footer = renderFooter(brief);

  return `${header}\n\n${top}${divider}${workingMemory}\n\n${footer}\n`;
}

function renderHeader(brief: HandoffBrief): string {
  const lines = [
    `# Handoff brief: ${brief.channelName}`,
    "",
    `**Channel id:** ${brief.channelId}`,
    `**Brief id:** ${brief.briefId}`,
    `**Generated at:** ${brief.generatedAt}`,
    `**From:** ${brief.fromProvider ?? "unknown"}${
      brief.fromSessionId ? ` (session ${brief.fromSessionId})` : ""
    }`,
    `**To:** ${brief.toHint ?? "(unspecified)"}`,
    `**Schema version:** ${brief.schemaVersion}`,
  ];
  if (brief.resumedFrom) {
    lines.push(
      `**Resumed from:** ${brief.resumedFrom.briefId} (originally generated ${formatDate(
        brief.resumedFrom.originalGeneratedAt
      )})`
    );
  }
  return lines.join("\n");
}

function renderSection(heading: string, body: string): string {
  return `## ${heading}\n\n${body}`;
}

function renderFooter(brief: HandoffBrief): string {
  const tag = "`rly handoff`";
  const dir = "`~/.relay/`";
  return (
    `*Generated by ${tag}. Sections above the divider are deterministic from ${dir}. ` +
    `The "Working memory" block was authored at ${brief.generatedAt}. ` +
    `Total token estimate: ${brief.tokenEstimate}.*`
  );
}

function formatDate(iso: string): string {
  const m = /^(\d{4}-\d{2}-\d{2})/.exec(iso);
  return m ? m[1] : iso;
}
