import { describe, expect, it } from "vitest";

import { renderBrief } from "../../../src/orchestrator/handoff/render-markdown.js";
import type { HandoffBrief } from "../../../src/orchestrator/handoff/types.js";

function makeBrief(overrides: Partial<HandoffBrief> = {}): HandoffBrief {
  const base: HandoffBrief = {
    schemaVersion: 1,
    briefId: "brief-1746789000000-abc123",
    channelId: "ch-fixmin-0001",
    channelName: "fixture-min",
    generatedAt: "2026-05-09T12:00:00.000Z",
    fromProvider: "claude",
    fromSessionId: "sess-fixsrc-0001",
    toHint: "codex",
    sections: {
      statusSnapshot: { heading: "Status snapshot", body: "tier: feature", estimatedTokens: 5 },
      mission: { heading: "Mission", body: "Test the synthesizer", estimatedTokens: 4 },
      ticketDag: { heading: "Ticket DAG", body: "T-1 done", estimatedTokens: 3 },
      recentDecisions: { heading: "Recent decisions", body: "d-001", estimatedTokens: 2 },
      filesTouched: {
        heading: "Files touched",
        body: "(no files-touched data)",
        estimatedTokens: 6,
      },
      workingMemory: {
        heading: "Working memory",
        body: "[gap-fill not provided]",
        estimatedTokens: 7,
      },
    },
    tokenEstimate: 27,
  };
  return { ...base, ...overrides };
}

describe("renderBrief — markdown rendering", () => {
  it("includes the canonical header with **Schema version:** 1", () => {
    const md = renderBrief(makeBrief());
    expect(md).toContain("# Handoff brief: fixture-min");
    expect(md).toContain("**Channel id:** ch-fixmin-0001");
    expect(md).toContain("**Schema version:** 1");
    expect(md).toContain("**Brief id:** brief-1746789000000-abc123");
  });

  it("renders sections in the canonical order (Status → Mission → Ticket DAG → Decisions → Files touched → Working memory)", () => {
    const md = renderBrief(makeBrief());
    const order = [
      md.indexOf("## Status snapshot"),
      md.indexOf("## Mission"),
      md.indexOf("## Ticket DAG"),
      md.indexOf("## Recent decisions"),
      md.indexOf("## Files touched"),
      md.indexOf("## Working memory"),
    ];
    for (let i = 0; i < order.length - 1; i++) {
      expect(order[i]).toBeGreaterThan(-1);
      expect(order[i + 1]).toBeGreaterThan(order[i]);
    }
  });

  it("inserts the M4 v1-lossy footnote at the end of the Files-touched section", () => {
    const md = renderBrief(makeBrief());
    expect(md).toContain(
      "> *(v1: files-touched is reconstructed from git log; uncommitted changes and tickets without commit references are missing. Tracked: D-02.)*"
    );
    // The footnote must come AFTER the Files-touched heading and BEFORE
    // the divider that introduces Working memory.
    const filesIdx = md.indexOf("## Files touched");
    const footIdx = md.indexOf("Tracked: D-02");
    const dividerIdx = md.indexOf("---");
    expect(footIdx).toBeGreaterThan(filesIdx);
    expect(dividerIdx).toBeGreaterThan(footIdx);
  });

  it("places Working memory below the `---` divider", () => {
    const md = renderBrief(makeBrief());
    const dividerIdx = md.indexOf("---");
    const wmIdx = md.indexOf("## Working memory");
    expect(wmIdx).toBeGreaterThan(dividerIdx);
  });

  it("renders **Resumed from:** when brief.resumedFrom is set (M7)", () => {
    const md = renderBrief(
      makeBrief({
        resumedFrom: {
          briefId: "brief-1746000000000-orig01",
          originalGeneratedAt: "2026-05-02T12:00:00.000Z",
        },
      })
    );
    expect(md).toContain("**Resumed from:** brief-1746000000000-orig01");
    expect(md).toContain("originally generated 2026-05-02");
  });

  it("renders footer with token estimate and `rly handoff` provenance", () => {
    const md = renderBrief(makeBrief());
    expect(md).toMatch(/Generated by `rly handoff`/);
    expect(md).toContain("Total token estimate: 27");
  });

  it("is byte-deterministic (two consecutive calls produce identical output)", () => {
    const brief = makeBrief();
    expect(renderBrief(brief)).toBe(renderBrief(brief));
  });
});
