import { mkdir, writeFile, chmod } from "node:fs/promises";
import { join } from "node:path";

import { getRelayDir } from "../cli/paths.js";

export async function generateHookScripts(): Promise<{
  shellScriptPath: string;
  nodeScriptPath: string;
}> {
  const relayDir = getRelayDir();
  // Hooks live under the legacy `crosslink/hooks` path so existing
  // `~/.claude/settings.json` entries (set up via past `rly crosslink init`
  // runs) continue to resolve to the same script location after this
  // migration. The script's *data* paths now point at the HarnessStore
  // layout.
  const hooksDir = join(relayDir, "crosslink", "hooks");
  await mkdir(hooksDir, { recursive: true });

  const shellScriptPath = join(hooksDir, "check-messages.sh");
  const nodeScriptPath = join(hooksDir, "check-messages.mjs");

  await writeFile(shellScriptPath, buildShellScript(nodeScriptPath));
  await chmod(shellScriptPath, 0o755);

  // Bake the relay root into the generated node script so it can find the
  // FileHarnessStore's `crosslink-session/` and `crosslink-mailbox/`
  // namespace directories at runtime without needing @relay/* module
  // resolution.
  await writeFile(nodeScriptPath, buildNodeScript(relayDir));

  return { shellScriptPath, nodeScriptPath };
}

function buildShellScript(nodeScriptPath: string): string {
  return `#!/bin/bash
# Crosslink message check hook — generated by Relay
# Checks for inbound crosslink messages and outputs them for context injection.

NODE="$(which node 2>/dev/null)"

if [ -z "$NODE" ]; then
  exit 0
fi

"$NODE" "${nodeScriptPath}" 2>/dev/null
`;
}

function buildNodeScript(relayDir: string): string {
  return `#!/usr/bin/env node
// Crosslink message check — generated by Relay
// Reads pending messages for the current session and outputs them for context injection.
//
// Data layout: the harness stores crosslink state through \`FileHarnessStore\`
// at \`<RELAY_DIR>/crosslink-session/<sessionId>.json\` and
// \`<RELAY_DIR>/crosslink-mailbox/<toSessionId>__<messageId>.json\`. This
// script reads those paths directly so it doesn't need module resolution
// into the installed harness bundle.

import { readdir, readFile, writeFile, rename } from "node:fs/promises";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const RELAY_DIR = ${JSON.stringify(relayDir)};
const SESSIONS_DIR = join(RELAY_DIR, "crosslink-session");
const MAILBOXES_DIR = join(RELAY_DIR, "crosslink-mailbox");
const MAILBOX_ID_SEPARATOR = "__";

async function main() {
  // Find our session by matching parent PID chain
  const sessions = await safeReaddir(SESSIONS_DIR);
  let mySession = null;

  for (const file of sessions) {
    if (!file.endsWith(".json")) continue;

    try {
      const raw = JSON.parse(await readFile(join(SESSIONS_DIR, file), "utf8"));

      if (raw.pid && isProcessAlive(raw.pid)) {
        // Check if this session's PID is an ancestor of our process
        // or if it matches our RELAY_SESSION env
        if (process.env.RELAY_SESSION === raw.sessionId) {
          mySession = raw;
          break;
        }

        // Fallback: use most recently heartbeated active session for this repo
        if (!mySession || raw.lastHeartbeat > mySession.lastHeartbeat) {
          mySession = raw;
        }
      }
    } catch {
      // Skip malformed session files
    }
  }

  if (!mySession) {
    process.exit(0);
  }

  // Read pending messages from the flat mailbox namespace, filtering by
  // \`<toSessionId>__\` prefix so we only see messages addressed to us.
  const prefix = \`\${mySession.sessionId}\${MAILBOX_ID_SEPARATOR}\`;
  const allMailboxFiles = await safeReaddir(MAILBOXES_DIR);
  const messageFiles = allMailboxFiles.filter(
    (f) => f.startsWith(prefix) && f.endsWith(".json")
  );
  const pendingMessages = [];

  for (const file of messageFiles) {
    try {
      const filePath = join(MAILBOXES_DIR, file);
      const msg = JSON.parse(await readFile(filePath, "utf8"));

      if (msg.status === "pending" && msg.toSessionId === mySession.sessionId) {
        pendingMessages.push({ msg, filePath });
      }
    } catch {
      // Skip malformed
    }
  }

  if (pendingMessages.length === 0) {
    process.exit(0);
  }

  // Output messages for context injection
  for (const { msg, filePath } of pendingMessages) {
    const replyHint = msg.type === "question"
      ? " — use crosslink_reply to respond"
      : "";

    console.log(\`[CROSSLINK INBOUND from=\${msg.fromSessionId} messageId=\${msg.messageId} type=\${msg.type}\${replyHint}]\`);
    console.log(msg.content);
    console.log("[/CROSSLINK]");
    console.log("");

    // Mark as delivered
    msg.status = "delivered";
    msg.deliveredAt = new Date().toISOString();

    const tmpPath = filePath + ".tmp." + process.pid;
    await writeFile(tmpPath, JSON.stringify(msg, null, 2));
    await rename(tmpPath, filePath);
  }

  // Notify via tmux if available
  if (process.env.TMUX) {
    try {
      execFileSync("tmux", [
        "display-message",
        \`Crosslink: \${pendingMessages.length} message(s) received\`
      ], { stdio: "ignore", timeout: 2000 });
    } catch {
      // tmux not available
    }
  }
}

function isProcessAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

async function safeReaddir(dir) {
  try {
    return await readdir(dir);
  } catch {
    return [];
  }
}

main().catch(() => process.exit(0));
`;
}

export function getClaudeHookConfig(shellScriptPath: string): object {
  return {
    hooks: {
      UserPromptSubmit: [
        {
          type: "command",
          command: shellScriptPath,
        },
      ],
    },
  };
}

export function printHookSetupInstructions(shellScriptPath: string): void {
  console.log("Crosslink hook scripts generated.");
  console.log("");
  console.log("For Claude Code, add this to your ~/.claude/settings.json:");
  console.log("");
  console.log(JSON.stringify(getClaudeHookConfig(shellScriptPath), null, 2));
  console.log("");
  console.log("For Codex, add this system prompt instruction to your codex config:");
  console.log(
    '  "At the start of each task, call crosslink_poll to check for messages from other sessions."'
  );
}
