import { mkdir, writeFile, chmod } from "node:fs/promises";
import { join } from "node:path";

import { getRelayDir } from "../cli/paths.js";

export async function generateHookScripts(): Promise<{
  shellScriptPath: string;
  nodeScriptPath: string;
}> {
  const crosslinkDir = join(getRelayDir(), "crosslink");
  const hooksDir = join(crosslinkDir, "hooks");
  await mkdir(hooksDir, { recursive: true });

  const shellScriptPath = join(hooksDir, "check-messages.sh");
  const nodeScriptPath = join(hooksDir, "check-messages.mjs");

  await writeFile(shellScriptPath, buildShellScript(nodeScriptPath));
  await chmod(shellScriptPath, 0o755);

  // Generate the standalone node script with the absolute crosslink directory
  // baked in at generation time. The script runs out-of-process so it can't
  // reach our path helper.
  await writeFile(nodeScriptPath, buildNodeScript(crosslinkDir));

  return { shellScriptPath, nodeScriptPath };
}

function buildShellScript(nodeScriptPath: string): string {
  return `#!/bin/bash
# Crosslink message check hook — generated by Relay
# Checks for inbound crosslink messages and outputs them for context injection.

NODE="$(which node 2>/dev/null)"

if [ -z "$NODE" ]; then
  exit 0
fi

"$NODE" "${nodeScriptPath}" 2>/dev/null
`;
}

function buildNodeScript(crosslinkDir: string): string {
  return `#!/usr/bin/env node
// Crosslink message check — generated by Relay
// Reads pending messages for the current session and outputs them for context injection.

import { readdir, readFile, writeFile, rename } from "node:fs/promises";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const CROSSLINK_DIR = ${JSON.stringify(crosslinkDir)};
const SESSIONS_DIR = join(CROSSLINK_DIR, "sessions");
const MAILBOXES_DIR = join(CROSSLINK_DIR, "mailboxes");

async function main() {
  // Find our session by matching parent PID chain
  const sessions = await safeReaddir(SESSIONS_DIR);
  let mySession = null;

  for (const file of sessions) {
    if (!file.endsWith(".json")) continue;

    try {
      const raw = JSON.parse(await readFile(join(SESSIONS_DIR, file), "utf8"));

      if (raw.pid && isProcessAlive(raw.pid)) {
        // Check if this session's PID is an ancestor of our process
        // or if it matches our RELAY_SESSION / AGENT_HARNESS_SESSION env
        if (
          process.env.RELAY_SESSION === raw.sessionId ||
          process.env.AGENT_HARNESS_SESSION === raw.sessionId
        ) {
          mySession = raw;
          break;
        }

        // Fallback: use most recently heartbeated active session for this repo
        if (!mySession || raw.lastHeartbeat > mySession.lastHeartbeat) {
          mySession = raw;
        }
      }
    } catch {
      // Skip malformed session files
    }
  }

  if (!mySession) {
    process.exit(0);
  }

  // Read pending messages
  const mailboxDir = join(MAILBOXES_DIR, mySession.sessionId);
  const messageFiles = await safeReaddir(mailboxDir);
  const pendingMessages = [];

  for (const file of messageFiles) {
    if (!file.endsWith(".json")) continue;

    try {
      const filePath = join(mailboxDir, file);
      const msg = JSON.parse(await readFile(filePath, "utf8"));

      if (msg.status === "pending") {
        pendingMessages.push({ msg, filePath });
      }
    } catch {
      // Skip malformed
    }
  }

  if (pendingMessages.length === 0) {
    process.exit(0);
  }

  // Output messages for context injection
  for (const { msg, filePath } of pendingMessages) {
    const replyHint = msg.type === "question"
      ? " — use crosslink_reply to respond"
      : "";

    console.log(\`[CROSSLINK INBOUND from=\${msg.fromSessionId} messageId=\${msg.messageId} type=\${msg.type}\${replyHint}]\`);
    console.log(msg.content);
    console.log("[/CROSSLINK]");
    console.log("");

    // Mark as delivered
    msg.status = "delivered";
    msg.deliveredAt = new Date().toISOString();

    const tmpPath = filePath + ".tmp." + process.pid;
    await writeFile(tmpPath, JSON.stringify(msg, null, 2));
    await rename(tmpPath, filePath);
  }

  // Notify via tmux if available
  if (process.env.TMUX) {
    try {
      execFileSync("tmux", [
        "display-message",
        \`Crosslink: \${pendingMessages.length} message(s) received\`
      ], { stdio: "ignore", timeout: 2000 });
    } catch {
      // tmux not available
    }
  }
}

function isProcessAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

async function safeReaddir(dir) {
  try {
    return await readdir(dir);
  } catch {
    return [];
  }
}

main().catch(() => process.exit(0));
`;
}

export function getClaudeHookConfig(shellScriptPath: string): object {
  return {
    hooks: {
      UserPromptSubmit: [
        {
          type: "command",
          command: shellScriptPath
        }
      ]
    }
  };
}

export function printHookSetupInstructions(shellScriptPath: string): void {
  console.log("Crosslink hook scripts generated.");
  console.log("");
  console.log("For Claude Code, add this to your ~/.claude/settings.json:");
  console.log("");
  console.log(JSON.stringify(getClaudeHookConfig(shellScriptPath), null, 2));
  console.log("");
  console.log("For Codex, add this system prompt instruction to your codex config:");
  console.log('  "At the start of each task, call crosslink_poll to check for messages from other sessions."');
}
