import { mkdir, writeFile, chmod } from "node:fs/promises";
import { join } from "node:path";

import { getRelayDir } from "../cli/paths.js";

export async function generateHookScripts(): Promise<{
  shellScriptPath: string;
  nodeScriptPath: string;
}> {
  const relayDir = getRelayDir();
  // Hooks live under the legacy `crosslink/hooks` path so existing
  // `~/.claude/settings.json` entries (set up via past `rly crosslink init`
  // runs) continue to resolve to the same script location after this
  // migration. The script's *data* paths now point at the HarnessStore
  // layout.
  const hooksDir = join(relayDir, "crosslink", "hooks");
  await mkdir(hooksDir, { recursive: true });

  const shellScriptPath = join(hooksDir, "check-messages.sh");
  const nodeScriptPath = join(hooksDir, "check-messages.mjs");

  await writeFile(shellScriptPath, buildShellScript(nodeScriptPath));
  await chmod(shellScriptPath, 0o755);

  // Bake the relay root into the generated node script so it can find the
  // FileHarnessStore's `crosslink-session/` and `crosslink-mailbox/`
  // namespace directories at runtime without needing @relay/* module
  // resolution.
  await writeFile(nodeScriptPath, buildNodeScript(relayDir));

  return { shellScriptPath, nodeScriptPath };
}

function buildShellScript(nodeScriptPath: string): string {
  return `#!/bin/bash
# Crosslink message check hook — generated by Relay
# Checks for inbound crosslink messages and outputs them for context injection.

NODE="$(which node 2>/dev/null)"

if [ -z "$NODE" ]; then
  exit 0
fi

"$NODE" "${nodeScriptPath}" 2>/dev/null
`;
}

function buildNodeScript(relayDir: string): string {
  return `#!/usr/bin/env node
// Crosslink message check — generated by Relay
// Reads pending messages for the current session and outputs them for context injection.
//
// Data layout: the harness stores crosslink state through \`FileHarnessStore\`
// at \`<RELAY_DIR>/crosslink-session/<sessionId>.json\` and
// \`<RELAY_DIR>/crosslink-mailbox/<toSessionId>__<messageId>.json\`. This
// script reads those paths directly so it doesn't need module resolution
// into the installed harness bundle.

import { readdir, readFile, writeFile, rename } from "node:fs/promises";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const RELAY_DIR = ${JSON.stringify(relayDir)};
const SESSIONS_DIR = join(RELAY_DIR, "crosslink-session");
const MAILBOXES_DIR = join(RELAY_DIR, "crosslink-mailbox");
const MAILBOX_ID_SEPARATOR = "__";

async function main() {
  // Find our session by matching parent PID chain
  const sessions = await safeReaddir(SESSIONS_DIR);
  let mySession = null;

  for (const file of sessions) {
    if (!file.endsWith(".json")) continue;

    try {
      const raw = JSON.parse(await readFile(join(SESSIONS_DIR, file), "utf8"));

      if (raw.pid && isProcessAlive(raw.pid)) {
        // Check if this session's PID is an ancestor of our process
        // or if it matches our RELAY_SESSION env
        if (process.env.RELAY_SESSION === raw.sessionId) {
          mySession = raw;
          break;
        }

        // Fallback: use most recently heartbeated active session for this repo
        if (!mySession || raw.lastHeartbeat > mySession.lastHeartbeat) {
          mySession = raw;
        }
      }
    } catch {
      // Skip malformed session files
    }
  }

  if (!mySession) {
    process.exit(0);
  }

  // Read pending messages from the flat mailbox namespace, filtering by
  // \`<toSessionId>__\` prefix so we only see messages addressed to us.
  const prefix = \`\${mySession.sessionId}\${MAILBOX_ID_SEPARATOR}\`;
  const allMailboxFiles = await safeReaddir(MAILBOXES_DIR);
  const messageFiles = allMailboxFiles.filter(
    (f) => f.startsWith(prefix) && f.endsWith(".json")
  );
  const pendingMessages = [];

  for (const file of messageFiles) {
    try {
      const filePath = join(MAILBOXES_DIR, file);
      const msg = JSON.parse(await readFile(filePath, "utf8"));

      if (msg.status === "pending" && msg.toSessionId === mySession.sessionId) {
        pendingMessages.push({ msg, filePath });
      }
    } catch {
      // Skip malformed
    }
  }

  if (pendingMessages.length === 0) {
    process.exit(0);
  }

  // Output messages for context injection
  for (const { msg, filePath } of pendingMessages) {
    const replyHint = msg.type === "question"
      ? " — use crosslink_reply to respond"
      : "";

    console.log(\`[CROSSLINK INBOUND from=\${msg.fromSessionId} messageId=\${msg.messageId} type=\${msg.type}\${replyHint}]\`);
    console.log(msg.content);
    console.log("[/CROSSLINK]");
    console.log("");

    // Mark as delivered
    msg.status = "delivered";
    msg.deliveredAt = new Date().toISOString();

    const tmpPath = filePath + ".tmp." + process.pid;
    await writeFile(tmpPath, JSON.stringify(msg, null, 2));
    await rename(tmpPath, filePath);
  }

  // Notify via tmux if available
  if (process.env.TMUX) {
    try {
      execFileSync("tmux", [
        "display-message",
        \`Crosslink: \${pendingMessages.length} message(s) received\`
      ], { stdio: "ignore", timeout: 2000 });
    } catch {
      // tmux not available
    }
  }
}

function isProcessAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

async function safeReaddir(dir) {
  try {
    return await readdir(dir);
  } catch {
    return [];
  }
}

main().catch(() => process.exit(0));
`;
}

export function getClaudeHookConfig(shellScriptPath: string): object {
  return {
    hooks: {
      UserPromptSubmit: [
        {
          type: "command",
          command: shellScriptPath,
        },
      ],
    },
  };
}

export function printHookSetupInstructions(shellScriptPath: string): void {
  console.log("Crosslink hook scripts generated.");
  console.log("");
  console.log("For Claude Code, add this to your ~/.claude/settings.json:");
  console.log("");
  console.log(JSON.stringify(getClaudeHookConfig(shellScriptPath), null, 2));
  console.log("");
  console.log("For Codex, add this system prompt instruction to your codex config:");
  console.log(
    '  "At the start of each task, call crosslink_poll to check for messages from other sessions."'
  );
}

// =========================================================================
// Phase 4 Plan 02: SessionStart hook generator
// =========================================================================
//
// Sibling to `generateHookScripts()` above. Emits a shell + node pair under
// `~/.relay/crosslink/hooks/session-start.{sh,mjs}` that Claude (and Codex,
// when the install wiring lands in Plan 03) runs on session start.
//
// The generated node script:
//   1. Resolves the active channel via `RELAY_CHANNEL_ID` env OR `cwd`-prefix
//      match against `channel.repoAssignments[].repoPath` (D-02).
//   2. Reads raw `~/.relay/crosslink-session/*.json` via direct fs (NEVER
//      `discoverSessions()` — Pitfall #3: would re-derive state and contradict
//      the canonical `derive_state` flow).
//   3. Computes `RepoAdminState` per repo via a TS-inlined mirror of
//      `deriveRepoAdminState` (single source of truth in
//      `src/domain/repo-admin-state.ts`; mirror byte-equivalence verified by
//      `generated_mjs_formatter_matches_TS_deriveRepoAdminState_for_all_4_states`
//      in `test/crosslink/session-start-hook.test.ts`).
//   4. Formats per `formatSessionStartContext` (inlined; see Task 1) and
//      prints to stdout — plain text, works for both Claude SessionStart and
//      Codex SessionStart (RESEARCH Pattern 3).
//   5. Exits 0 on success AND on any failure path (Pitfall #2 graceful
//      no-op — hook is best-effort surface, never block session start).

/**
 * Emit `~/.relay/crosslink/hooks/session-start.{sh,mjs}` and return both
 * paths. Mirrors {@link generateHookScripts} exactly: ensures the hooks
 * directory exists, writes the shell wrapper + node script, chmod 755s the
 * shell file, returns both paths.
 */
export async function generateSessionStartHookScripts(): Promise<{
  shellScriptPath: string;
  nodeScriptPath: string;
}> {
  const relayDir = getRelayDir();
  // Same hooks dir as the existing crosslink hook so install logic can scan
  // a single directory for both entries.
  const hooksDir = join(relayDir, "crosslink", "hooks");
  await mkdir(hooksDir, { recursive: true });

  const shellScriptPath = join(hooksDir, "session-start.sh");
  const nodeScriptPath = join(hooksDir, "session-start.mjs");

  await writeFile(shellScriptPath, buildSessionStartShellScript(nodeScriptPath));
  await chmod(shellScriptPath, 0o755);

  // Bake the relay root into the generated node script so it can find
  // `channels/<id>/channel.json`, `crosslink-session/<id>.json`, and
  // `channels/<id>/feed.jsonl` without needing module resolution.
  await writeFile(nodeScriptPath, buildSessionStartNodeScript(relayDir));

  return { shellScriptPath, nodeScriptPath };
}

function buildSessionStartShellScript(nodeScriptPath: string): string {
  return `#!/bin/bash
# Relay SessionStart hook — generated by Relay (Phase 4 Plan 02)
# Resolves the active channel from the current cwd / RELAY_CHANNEL_ID,
# reads per-repo CrosslinkSession state, and prints a brief context block
# into the agent's first turn (Claude SessionStart / Codex equivalent).
#
# Always exits 0 — failures must not block the session from starting.

NODE="$(which node 2>/dev/null)"

if [ -z "$NODE" ]; then
  exit 0
fi

"$NODE" "${nodeScriptPath}" 2>/dev/null
exit 0
`;
}

function buildSessionStartNodeScript(relayDir: string): string {
  // The node script is intentionally self-contained — no third-party imports,
  // no module-resolution dance into the installed harness bundle. The
  // formatter, state-derivation logic, and isProcessAlive shim are all
  // inlined as plain JS. Tests in `test/crosslink/session-start-hook.test.ts`
  // execute this script against a tmpdir-rooted relay fixture; the
  // behavioral-equivalence test cross-checks the inlined state derivation
  // against the TS reference `deriveRepoAdminState`.
  //
  // KEEP IN SYNC: any change to `formatSessionStartContext`
  // (`src/crosslink/session-start-hook-content.ts`) or `deriveRepoAdminState`
  // (`src/domain/repo-admin-state.ts`) MUST be mirrored here. The
  // STALE_HEARTBEAT_MS constant, the branch order in derive_state, and the
  // four-state vocabulary all live in three places; the script-template test
  // for `STALE_HEARTBEAT_MS = 120_000` is the guardrail.
  return `#!/usr/bin/env node
// Relay SessionStart hook — generated by Relay (Phase 4 Plan 02)
// Resolves the active channel via RELAY_CHANNEL_ID or cwd-prefix match,
// derives per-repo state from CrosslinkSession records, and prints a
// brief context block. Exits 0 always.

import { readdir, readFile, writeFile, rename } from "node:fs/promises";
import { join } from "node:path";

// RELAY_DIR is baked at generation time but can be overridden via the env
// for tests (the end-to-end test in test/crosslink/session-start-hook.test.ts
// drives the script against a tmpdir-rooted ~/.relay/ fixture).
const RELAY_DIR = process.env.RELAY_DIR || ${JSON.stringify(relayDir)};
const CHANNELS_DIR = join(RELAY_DIR, "channels");
const SESSIONS_DIR = join(RELAY_DIR, "crosslink-session");

// Inlined mirror of STALE_HEARTBEAT_MS from src/domain/repo-admin-state.ts.
// Keep in sync — drift caught by the script-template grep test for the
// literal "STALE_HEARTBEAT_MS = 120_000".
const STALE_HEARTBEAT_MS = 120_000;

function isProcessAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

// Inlined mirror of deriveRepoAdminState from src/domain/repo-admin-state.ts.
// Branch order MUST match the TS reference byte-for-byte:
//   1. session === null  → "disconnected"
//   2. !alive || heartbeat aged > STALE_HEARTBEAT_MS → "stale" (stale wins
//      over ready: a session whose pid is dead is stale even if readyAt set).
//   3. readyAt truthy    → "ready"
//   4. otherwise         → "booting"
function deriveRepoAdminState(session, nowMs) {
  if (!session) return "disconnected";
  const hb = new Date(session.lastHeartbeat).getTime();
  const alive = isProcessAlive(session.pid);
  if (!alive || nowMs - hb > STALE_HEARTBEAT_MS) return "stale";
  if (session.readyAt) return "ready";
  return "booting";
}

// Inlined mirror of glyphFor / detailFor / formatSessionStartContext from
// src/crosslink/session-start-hook-content.ts. The behavioral-equivalence
// test compares the state word emitted here against the TS reference for the
// 4-state truth-table fixture; the formatter shape is also exercised by the
// end-to-end stdout assertions.
function glyphFor(state) {
  switch (state) {
    case "ready": return "●";
    case "booting": return "○";
    case "stale": return "×";
    case "disconnected": return "·";
    default: return "·";
  }
}

function formatRelative(ms) {
  if (ms < 0) return "0s";
  const seconds = Math.floor(ms / 1000);
  if (seconds < 60) return seconds + "s";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return minutes + "m";
  const hours = Math.floor(minutes / 60);
  return hours + "h";
}

function detailFor(repo) {
  switch (repo.state) {
    case "ready":
      return repo.adminAlias ? " (admin: " + repo.adminAlias + ")" : "";
    case "booting":
      if (typeof repo.bootingSinceMs !== "number") return "";
      return " (since " + formatRelative(repo.bootingSinceMs) + " ago)";
    case "stale":
      return " (stale)";
    case "disconnected":
      return "";
    default:
      return "";
  }
}

function formatSessionStartContext(channelName, repoStates, newFeedEntries) {
  if (repoStates.length === 0) return "";
  const lines = [];
  lines.push("[Relay] Channel: " + channelName + " (" + repoStates.length + " repos)");
  for (const repo of repoStates) {
    const glyph = glyphFor(repo.state);
    const alias = repo.alias.padEnd(14);
    const detail = detailFor(repo);
    lines.push("  " + glyph + " " + alias + " " + repo.state + detail);
  }
  if (typeof newFeedEntries === "number" && newFeedEntries > 0) {
    lines.push(
      "Feed: " + newFeedEntries +
        " new entries since you were last here. Use \\\`rly status\\\` for detail."
    );
  }
  return lines.join("\\n");
}

async function safeReaddir(dir) {
  try {
    return await readdir(dir);
  } catch {
    return [];
  }
}

async function readJsonOrNull(path) {
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch {
    return null;
  }
}

/**
 * Resolve the active channel per D-02:
 *   (a) RELAY_CHANNEL_ID env set → read channels/<id>.json directly.
 *   (b) Else: enumerate channels/*.json, filter status === "active",
 *       pick those whose repoAssignments[].repoPath exactly matches cwd
 *       or is a path-prefix (cwd.startsWith(ra.repoPath + "/")). Tie-break
 *       by updatedAt descending (RESEARCH Pattern 4 — most-recent wins).
 *   (c) Neither resolves → null (caller exits 0 with empty stdout).
 */
async function resolveActiveChannel(cwd) {
  // Path (a): explicit env. Single read, no enumeration cost.
  if (process.env.RELAY_CHANNEL_ID) {
    const channel = await readJsonOrNull(
      join(CHANNELS_DIR, process.env.RELAY_CHANNEL_ID + ".json")
    );
    if (channel) return channel;
    // Fall through to (b) — env id may be stale, cwd may still resolve.
  }

  // Path (b): cwd reverse lookup.
  const files = await safeReaddir(CHANNELS_DIR);
  const candidates = [];
  for (const file of files) {
    if (!file.endsWith(".json")) continue;
    const channel = await readJsonOrNull(join(CHANNELS_DIR, file));
    if (!channel) continue;
    if (channel.status && channel.status !== "active") continue;
    const assignments = Array.isArray(channel.repoAssignments) ? channel.repoAssignments : [];
    let matched = false;
    for (const ra of assignments) {
      if (!ra || typeof ra.repoPath !== "string") continue;
      if (cwd === ra.repoPath || cwd.startsWith(ra.repoPath + "/")) {
        matched = true;
        break;
      }
    }
    if (matched) candidates.push(channel);
  }
  if (candidates.length === 0) return null;
  // Tie-break by most-recent updatedAt — single-channel cwd resolves
  // cleanly; multi-channel cwd picks the freshest.
  candidates.sort((a, b) => (b.updatedAt || "").localeCompare(a.updatedAt || ""));
  return candidates[0];
}

async function readAllSessions() {
  const files = await safeReaddir(SESSIONS_DIR);
  const sessions = [];
  for (const file of files) {
    if (!file.endsWith(".json")) continue;
    const raw = await readJsonOrNull(join(SESSIONS_DIR, file));
    if (raw && typeof raw === "object") sessions.push(raw);
  }
  return sessions;
}

/**
 * Atomic-rename watermark write. Best-effort: failures swallowed so a
 * disk error doesn't make the agent's first-turn render fail.
 */
async function advanceWatermark(sessionId, idx) {
  try {
    const sessionPath = join(SESSIONS_DIR, sessionId + ".json");
    const raw = await readJsonOrNull(sessionPath);
    if (!raw) return;
    const current = typeof raw.lastSeenFeedIdx === "number" ? raw.lastSeenFeedIdx : 0;
    if (idx <= current) return; // monotonic
    raw.lastSeenFeedIdx = idx;
    const tmpPath = sessionPath + ".tmp." + process.pid;
    await writeFile(tmpPath, JSON.stringify(raw, null, 2));
    await rename(tmpPath, sessionPath);
  } catch {
    // best-effort
  }
}

async function main() {
  // Drain stdin (Claude/Codex pipe JSON). We don't need the payload for the
  // current resolution rules — cwd comes from process.cwd(); env vars from
  // process.env. Drain anyway so the parent isn't left with an unclosed pipe.
  let stdinPayload = null;
  try {
    if (!process.stdin.isTTY) {
      const chunks = [];
      for await (const chunk of process.stdin) chunks.push(chunk);
      const text = Buffer.concat(chunks).toString("utf8").trim();
      if (text) {
        try {
          stdinPayload = JSON.parse(text);
        } catch {
          stdinPayload = null;
        }
      }
    }
  } catch {
    stdinPayload = null;
  }

  const cwd =
    (stdinPayload && typeof stdinPayload.cwd === "string" && stdinPayload.cwd) ||
    process.cwd();

  const channel = await resolveActiveChannel(cwd);
  if (!channel) {
    process.exit(0);
  }

  const nowMs = Date.now();
  const allSessions = await readAllSessions();
  // Pitfall #6: filter sessions to THIS channel only — never enumerate the
  // full set. Channels with no channelId on the session record are skipped
  // (legacy / non-channel sessions don't surface here).
  const channelSessions = allSessions.filter((s) => s && s.channelId === channel.channelId);

  // Build per-repo state rows. Iteration order matches repoAssignments to
  // give a stable rendering.
  const assignments = Array.isArray(channel.repoAssignments) ? channel.repoAssignments : [];
  const repoStates = [];
  for (const ra of assignments) {
    if (!ra || typeof ra.alias !== "string") continue;
    // Match session to repo by repoPath. Best-effort: a channel with two
    // workspaces pointing at the same repoPath would land on the
    // most-recent-heartbeat session.
    const matches = channelSessions.filter((s) => s && s.repoPath === ra.repoPath);
    matches.sort((a, b) => (b.lastHeartbeat || "").localeCompare(a.lastHeartbeat || ""));
    const session = matches[0] || null;
    const state = deriveRepoAdminState(session, nowMs);
    const row = { alias: ra.alias, state };
    if (state === "ready" && session) {
      // displayName carries the human-readable agent alias (atlas-7f2 etc).
      // Fall back to repoAlias / sessionId fragments when absent.
      row.adminAlias =
        (typeof session.displayName === "string" && session.displayName) ||
        (typeof session.alias === "string" && session.alias) ||
        undefined;
    }
    if (state === "booting" && session) {
      const start = new Date(session.registeredAt || session.lastHeartbeat).getTime();
      if (Number.isFinite(start)) row.bootingSinceMs = nowMs - start;
    }
    repoStates.push(row);
  }

  // Feed-tail gate: only when RELAY_SESSION_ID is set AND matches a record
  // we can read a watermark off. User-launched (non-Relay-spawned) sessions
  // have no watermark anchor — emitting "Feed: N new entries" every start
  // would be noisy and dishonest. Omit instead.
  let newFeedEntries;
  let mySession = null;
  if (process.env.RELAY_SESSION_ID) {
    mySession = allSessions.find((s) => s && s.sessionId === process.env.RELAY_SESSION_ID) || null;
  }
  if (mySession) {
    try {
      const feedPath = join(CHANNELS_DIR, channel.channelId, "feed.jsonl");
      const raw = await readFile(feedPath, "utf8");
      // Pitfall #4: torn last line tolerance — filter(Boolean) drops empties.
      const totalEntries = raw.split("\\n").filter(Boolean).length;
      const seen = typeof mySession.lastSeenFeedIdx === "number" ? mySession.lastSeenFeedIdx : 0;
      const diff = totalEntries - seen;
      if (diff > 0) newFeedEntries = diff;
      // Advance watermark after we've computed the diff (best-effort write).
      await advanceWatermark(mySession.sessionId, totalEntries);
    } catch {
      // No feed file or read error — omit tail.
    }
  }

  const out = formatSessionStartContext(channel.name, repoStates, newFeedEntries);
  if (out) process.stdout.write(out + "\\n");
  process.exit(0);
}

main().catch(() => process.exit(0));
`;
}

/**
 * Build the Claude `settings.json` snippet that registers the SessionStart
 * hook. Symmetrical to {@link getClaudeHookConfig} for UserPromptSubmit.
 * Plan 03 (install integration) wires this into `rly install`.
 */
export function getClaudeSessionStartHookConfig(shellScriptPath: string): object {
  return {
    hooks: {
      SessionStart: [
        {
          type: "command",
          command: shellScriptPath,
        },
      ],
    },
  };
}
