import type { SessionLifecycle } from "../lifecycle/session-lifecycle.js";
import type { TokenTracker } from "../budget/token-tracker.js";
import type { Channel, RepoAssignment } from "../domain/channel.js";
import { RepoAdminPool } from "./repo-admin-pool.js";

/**
 * Options handed to {@link startAutonomousSession} by the CLI entrypoint
 * (`rly run --autonomous`, AL-3). AL-3 constructs the session scaffolding —
 * lifecycle, token tracker, audit decision entry, allowed-repo filter — and
 * then delegates actual ticket dispatch + driver loop to the function below.
 *
 * AL-4 owns the real implementation. This file ships a stub that logs a
 * "driver not yet implemented" message, transitions the lifecycle to
 * `killed`, and returns cleanly so the CLI can exit 0. Anything the driver
 * needs at steady state — scheduler access, approval queue, kill-switch
 * polling, pr-review integration, audit agent — is AL-4's problem, not
 * AL-3's, and must NOT creep into the stub body.
 */
export interface StartAutonomousSessionOptions {
  /** Session id generated by the CLI; shared by tracker + lifecycle + audit. */
  sessionId: string;
  /** The channel whose ticket board this session executes against. */
  channel: Channel;
  /** Token-budget tracker. Caller keeps ownership; AL-4 records against it. */
  tracker: TokenTracker;
  /** Lifecycle state machine. Caller has already transitioned it into
   * `dispatching`; AL-4's driver owns subsequent transitions. */
  lifecycle: SessionLifecycle;
  /** Trust mode as selected on the CLI. The stub records it but never acts
   * on it. AL-5 / AL-7 gate the real behaviour difference between
   * `supervised` and `god`. */
  trust: "supervised" | "god";
  /** Repo assignments the session is allowed to dispatch work into. Either
   * the subset selected by `--allow-repo` or — when the flag is absent —
   * every assignment on the channel. AL-4 uses this as a filter at dispatch
   * time. */
  allowedRepos: RepoAssignment[];
}

/**
 * Autonomous-loop driver entrypoint. AL-4 replaces this stub's body with
 * the real scheduler + dispatcher loop. Today (AL-3) it:
 *
 *   1. Logs a one-line "driver not yet implemented" message so operators
 *      who invoke `rly run --autonomous` on a version without AL-4 get a
 *      loud, expected signal rather than silent success.
 *   2. Transitions the lifecycle to `killed` with reason `"al-4-pending"`
 *      so the persisted `lifecycle.json` reflects a terminal state. Without
 *      this, a subsequent `rly run --autonomous` against the same session
 *      directory would replay a non-terminal state and the watchdog would
 *      still be armed.
 *   3. Drains queued writes via `close()` on both the tracker and the
 *      lifecycle so no disk IO races the process exit.
 *
 * Errors during the stub's own shutdown path are swallowed — the CLI
 * already logged a session-start decision, and a cosmetic teardown failure
 * must not turn a successful `rly run --autonomous` handoff into a non-zero
 * exit.
 */
export async function startAutonomousSession(opts: StartAutonomousSessionOptions): Promise<void> {
  const { sessionId, lifecycle, tracker, channel, allowedRepos } = opts;

  console.log(
    `[autonomous-loop] dispatcher not yet implemented — booting repo-admin ` +
      `pool then exiting. Session ${sessionId} marked as killed with reason ` +
      `"al-13-pending".`
  );

  // AL-12 boots one repo-admin per allowed repoAssignment. AL-13 adds the
  // ticket router that sends work to these sessions; until then we stand
  // them up to exercise the boot/shutdown path and return.
  const allowedAliases = allowedRepos.map((r) => r.alias);
  const pool = new RepoAdminPool({
    channel,
    allowedAliases,
    fullAccess: channel.fullAccess ?? false,
    lifecycle,
  });

  try {
    await pool.start();
  } catch (err) {
    console.warn(
      `[autonomous-loop] repo-admin pool failed to boot: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }

  // Only transition if we're still in a non-terminal state. A concurrent
  // threshold crossing or watchdog fire could theoretically have already
  // pushed us to `killed`; respect that and skip the transition in that
  // case to avoid throwing a LifecycleTransitionError the caller would
  // have to catch.
  const state = lifecycle.state;
  if (state !== "killed" && state !== "done") {
    try {
      await lifecycle.transition("killed", "al-13-pending");
    } catch (err) {
      console.warn(
        `[autonomous-loop] failed to transition lifecycle to killed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // Terminal lifecycle transition triggers the pool's auto-stop, but also
  // await it here so teardown happens before the CLI returns.
  try {
    await pool.stop();
  } catch (err) {
    console.warn(
      `[autonomous-loop] repo-admin pool stop failed: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }

  // Close out resources. Any in-flight writes drain here; errors are
  // warned but never thrown — the CLI exit path is the wrong place to
  // surface a teardown failure.
  try {
    await lifecycle.close();
  } catch (err) {
    console.warn(
      `[autonomous-loop] lifecycle close failed: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }
  try {
    await tracker.close();
  } catch (err) {
    console.warn(
      `[autonomous-loop] tracker close failed: ${err instanceof Error ? err.message : String(err)}`
    );
  }
}
