import type { SessionLifecycle } from "../lifecycle/session-lifecycle.js";
import type { TokenTracker } from "../budget/token-tracker.js";
import type { Channel, RepoAssignment } from "../domain/channel.js";
import { ChannelStore } from "../channels/channel-store.js";
import { RepoAdminPool, isRepoAdminPoolEnabled } from "./repo-admin-pool.js";
import { TicketRouter } from "./ticket-router.js";
import { TicketRunner } from "./ticket-runner.js";
import { WorkerSpawner } from "./worker-spawner.js";

/**
 * Options handed to {@link startAutonomousSession} by the CLI entrypoint
 * (`rly run --autonomous`, AL-3). AL-3 constructs the session scaffolding —
 * lifecycle, token tracker, audit decision entry, allowed-repo filter — and
 * then delegates actual ticket dispatch + driver loop to the function below.
 *
 * AL-4 owns the real implementation. This file ships a stub that logs a
 * "driver not yet implemented" message, transitions the lifecycle to
 * `killed`, and returns cleanly so the CLI can exit 0. Anything the driver
 * needs at steady state — scheduler access, approval queue, kill-switch
 * polling, pr-review integration, audit agent — is AL-4's problem, not
 * AL-3's, and must NOT creep into the stub body.
 */
export interface StartAutonomousSessionOptions {
  /** Session id generated by the CLI; shared by tracker + lifecycle + audit. */
  sessionId: string;
  /** The channel whose ticket board this session executes against. */
  channel: Channel;
  /** Token-budget tracker. Caller keeps ownership; AL-4 records against it. */
  tracker: TokenTracker;
  /** Lifecycle state machine. Caller has already transitioned it into
   * `dispatching`; AL-4's driver owns subsequent transitions. */
  lifecycle: SessionLifecycle;
  /** Trust mode as selected on the CLI. The stub records it but never acts
   * on it. AL-5 / AL-7 gate the real behaviour difference between
   * `supervised` and `god`. */
  trust: "supervised" | "god";
  /** Repo assignments the session is allowed to dispatch work into. Either
   * the subset selected by `--allow-repo` or — when the flag is absent —
   * every assignment on the channel. AL-4 uses this as a filter at dispatch
   * time. */
  allowedRepos: RepoAssignment[];
}

/**
 * Autonomous-loop driver entrypoint. At AL-14 the loop:
 *
 *   1. When {@link RELAY_REPO_ADMIN_POOL_ENABLED} is on:
 *      - Boots the repo-admin pool (AL-12).
 *      - Reads the channel's ticket board and routes each ready ticket
 *        through {@link TicketRouter} so the matching repo-admin queues
 *        it (AL-13).
 *      - For each admin, drains its pending queue via {@link TicketRunner}:
 *        spawn a worker in a per-ticket worktree, monitor until the
 *        worker exits, and mark the ticket `verifying` (PR opened) /
 *        `failed` (AC4) on the board. Serialized inside each admin;
 *        parallel across admins.
 *      - Transitions the lifecycle to `killed` with reason
 *        `"al-16-pending"`. AL-14 owns spawn + drain; inter-admin
 *        coordination + the steady-state driver loop are still pending.
 *   2. When the flag is off: preserves the pre-AL-13 behaviour — no pool,
 *      no routing, lifecycle transitions to `killed / al-13-pending`.
 *   3. Tears down pool + lifecycle + tracker. Errors during teardown are
 *      logged and swallowed: a cosmetic shutdown failure must not turn a
 *      successful handoff into a non-zero CLI exit.
 *
 * PR-merge cleanup (AC3) is NOT driven here — the runner exposes
 * {@link TicketRunner.handlePrMerged}; the autonomous-loop's steady-
 * state driver (AL-4) will plumb PR-poller merge events into that hook
 * once the loop runs long enough to observe them. AL-14's single-pass
 * autonomous stub intentionally exits before any PR can merge, so the
 * hook is dormant here.
 */
export async function startAutonomousSession(opts: StartAutonomousSessionOptions): Promise<void> {
  const { sessionId, lifecycle, tracker, channel, allowedRepos } = opts;

  // AL-12 built the repo-admin pool, but the admin-process handshake
  // protocol it relies on is AL-14's deliverable. Without that protocol
  // the default spawner's child exits in ms (no prompt, stdin closed)
  // and the pool flaps until the rapid-restart ceiling fires. Gate pool
  // construction behind RELAY_REPO_ADMIN_POOL_ENABLED so production
  // `rly run --autonomous` invocations keep the pre-AL-12 behaviour
  // (clean `killed / al-13-pending` exit) until AL-14 flips the flag.
  const poolEnabled = isRepoAdminPoolEnabled();

  if (!poolEnabled) {
    console.log(
      `[autonomous-loop] dispatcher not yet implemented — ` +
        `Session ${sessionId} marked as killed with reason "al-13-pending".`
    );
  } else {
    console.log(
      `[autonomous-loop] routing channel tickets + draining repo-admin queues — ` +
        `Session ${sessionId} will mark killed with reason "al-16-pending" once drained.`
    );
  }

  const pool = poolEnabled
    ? new RepoAdminPool({
        channel,
        allowedAliases: allowedRepos.map((r) => r.alias),
        fullAccess: channel.fullAccess ?? false,
        lifecycle,
      })
    : null;

  if (pool) {
    try {
      await pool.start();
    } catch (err) {
      console.warn(
        `[autonomous-loop] repo-admin pool failed to boot: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // AL-13: drain the channel's ticket board through the router exactly
  // once. AL-14 adds a second pass that drains each admin's queue via
  // TicketRunner — spawn a worker per ticket, wait for it to open a PR
  // (or fail), then exit. The autonomous-loop's steady-state driver
  // (AL-4) will replace this single-pass shape; AL-14 just proves the
  // end-to-end plumbing.
  let terminalReason: "al-13-pending" | "al-16-pending" = "al-13-pending";
  if (pool) {
    terminalReason = "al-16-pending";
    const runners: TicketRunner[] = [];
    try {
      const channelStore = new ChannelStore();
      const router = new TicketRouter({ pool, channel, channelStore });
      const boardTickets = await channelStore.readChannelTickets(channel.channelId);
      for (const ticket of boardTickets) {
        if (ticket.status !== "ready") continue;
        if (ticket.source === "linear") continue; // Linear mirror is read-only.
        try {
          const result = await router.route(ticket);
          if (result.kind === "unroutable") {
            console.warn(
              `[autonomous-loop] ticket ${ticket.ticketId} unroutable (${result.reason}); ` +
                `surfaced to channel board as blocked.`
            );
          }
        } catch (err) {
          console.warn(
            `[autonomous-loop] router threw on ticket ${ticket.ticketId}: ${
              err instanceof Error ? err.message : String(err)
            }`
          );
        }
      }

      // AL-14: drain each admin's pending queue in parallel. Each admin
      // serializes internally (one worker at a time in its repo); two
      // different admins DO run in parallel. The drain promise resolves
      // once every admin's queue is empty AND every in-flight worker has
      // exited.
      const spawner = new WorkerSpawner();
      const admins = pool.listSessions();
      for (const admin of admins) {
        const assignment = channel.repoAssignments?.find((a) => a.alias === admin.alias);
        if (!assignment) continue;
        runners.push(
          new TicketRunner({
            admin,
            repoAssignment: assignment,
            channel,
            channelStore,
            spawner,
          })
        );
      }
      await Promise.all(
        runners.map((r) =>
          r.drain().catch((err) => {
            console.warn(
              `[autonomous-loop] ticket runner drain failed: ${
                err instanceof Error ? err.message : String(err)
              }`
            );
          })
        )
      );
    } catch (err) {
      console.warn(
        `[autonomous-loop] ticket routing pass failed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    } finally {
      // Ensure any in-flight worker is signalled before we unwind. Safe
      // to call even if drain() already finished — stop() is idempotent
      // and only hits still-running workers.
      await Promise.all(
        runners.map((r) =>
          r.stop("autonomous-loop-exit").catch((err) => {
            console.warn(
              `[autonomous-loop] runner stop failed: ${
                err instanceof Error ? err.message : String(err)
              }`
            );
          })
        )
      );
    }
  }

  // Only transition if we're still in a non-terminal state. A concurrent
  // threshold crossing or watchdog fire could theoretically have already
  // pushed us to `killed`; respect that and skip the transition in that
  // case to avoid throwing a LifecycleTransitionError the caller would
  // have to catch.
  const state = lifecycle.state;
  if (state !== "killed" && state !== "done") {
    try {
      await lifecycle.transition("killed", terminalReason);
    } catch (err) {
      console.warn(
        `[autonomous-loop] failed to transition lifecycle to killed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // Terminal lifecycle transition triggers the pool's auto-stop, but also
  // await it here so teardown happens before the CLI returns.
  if (pool) {
    try {
      await pool.stop();
    } catch (err) {
      console.warn(
        `[autonomous-loop] repo-admin pool stop failed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // Close out resources. Any in-flight writes drain here; errors are
  // warned but never thrown — the CLI exit path is the wrong place to
  // surface a teardown failure.
  try {
    await lifecycle.close();
  } catch (err) {
    console.warn(
      `[autonomous-loop] lifecycle close failed: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }
  try {
    await tracker.close();
  } catch (err) {
    console.warn(
      `[autonomous-loop] tracker close failed: ${err instanceof Error ? err.message : String(err)}`
    );
  }
}
