import type { SessionLifecycle } from "../lifecycle/session-lifecycle.js";
import type { TokenTracker } from "../budget/token-tracker.js";
import type { Channel, RepoAssignment } from "../domain/channel.js";
import { ChannelStore } from "../channels/channel-store.js";
import { Coordinator } from "../crosslink/coordinator.js";
import { runPostCompletionAudit, type AuditInvoker, type AuditRunResult } from "./audit-agent.js";
import { RepoAdminPool, isRepoAdminPoolEnabled } from "./repo-admin-pool.js";
import type { RepoAdminProcessSpawner } from "./repo-admin-session.js";
import {
  DEFAULT_STOP_POLL_INTERVAL_MS,
  STOP_FILE_REASON,
  checkForStop,
  clearStopFile,
} from "./stop-file-watcher.js";
import { TicketRouter } from "./ticket-router.js";
import { TicketRunner } from "./ticket-runner.js";
import { WorkerSpawner } from "./worker-spawner.js";

/**
 * Env var gating AL-14's worker-drain phase. Distinct from the pool-enabled
 * flag so an operator can flip the pool on (AL-12 boot/restart/shutdown
 * exercise) without automatically enabling worker spawning + drain. The
 * split exists because AL-4's merge-detection cleanup has not shipped yet:
 * every worker that reaches `awaiting-merge` state leaves its worktree on
 * disk until AL-4 lands, and we want operators to opt into that leak
 * deliberately. Default **off**.
 *
 * Recognised true-ish values: `"1"`, `"true"`, `"yes"`, `"on"`
 * (case-insensitive). Anything else — including typos — is treated as off
 * so a misconfigured flag doesn't silently leak worktrees.
 */
export const RELAY_AL14_WORKER_DRAIN = "RELAY_AL14_WORKER_DRAIN";

/**
 * Parse {@link RELAY_AL14_WORKER_DRAIN} into a bool. See the constant's
 * docstring for the "why two flags" rationale.
 */
export function isWorkerDrainEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  const raw = env[RELAY_AL14_WORKER_DRAIN];
  if (!raw) return false;
  const normalized = raw.trim().toLowerCase();
  return normalized === "1" || normalized === "true" || normalized === "yes" || normalized === "on";
}

/**
 * Options handed to {@link startAutonomousSession} by the CLI entrypoint
 * (`rly run --autonomous`, AL-3). AL-3 constructs the session scaffolding —
 * lifecycle, token tracker, audit decision entry, allowed-repo filter — and
 * then delegates actual ticket dispatch + driver loop to the function below.
 *
 * AL-4 owns the real implementation. This file ships a stub that logs a
 * "driver not yet implemented" message, transitions the lifecycle to
 * `killed`, and returns cleanly so the CLI can exit 0. Anything the driver
 * needs at steady state — scheduler access, approval queue, kill-switch
 * polling, pr-review integration, audit agent — is AL-4's problem, not
 * AL-3's, and must NOT creep into the stub body.
 */
export interface StartAutonomousSessionOptions {
  /** Session id generated by the CLI; shared by tracker + lifecycle + audit. */
  sessionId: string;
  /** The channel whose ticket board this session executes against. */
  channel: Channel;
  /** Token-budget tracker. Caller keeps ownership; AL-4 records against it. */
  tracker: TokenTracker;
  /** Lifecycle state machine. Caller has already transitioned it into
   * `dispatching`; AL-4's driver owns subsequent transitions. */
  lifecycle: SessionLifecycle;
  /** Trust mode as selected on the CLI. AL-7 supplies the trust-mode gate
   * (`src/approvals/trust-gate.ts`) that every ack-requiring call site (PR
   * auto-merge from AL-5, audit-proposed ticket from AL-6) threads this
   * value into. Under `supervised`, ack-requiring actions are written to
   * `~/.relay/approvals/<sessionId>/queue.jsonl`; under `god` with
   * `RELAY_AL7_GOD_AUTOMERGE=1`, they execute directly. See
   * {@link "../approvals/trust-gate".decide}. */
  trust: "supervised" | "god";
  /** Repo assignments the session is allowed to dispatch work into. Either
   * the subset selected by `--allow-repo` or — when the flag is absent —
   * every assignment on the channel. AL-4 uses this as a filter at dispatch
   * time. */
  allowedRepos: RepoAssignment[];
  /**
   * AL-9: poll cadence for the STOP-file kill switch. The driver checks
   * `~/.relay/sessions/<sessionId>/STOP` before each dispatch tick and
   * transitions the lifecycle to `winding_down` when the file appears.
   * Defaults to {@link DEFAULT_STOP_POLL_INTERVAL_MS} (20s) matching the
   * AL-9 acceptance criterion "within one tick (≤20s)". Tests override
   * to a small value so the stop signal is picked up quickly.
   */
  stopPollIntervalMs?: number;
  /**
   * **Test-only** injection hooks. Production callers MUST NOT set these —
   * they exist solely so the AL-14 drain integration test can exercise the
   * pool-boot + router + runner drain path end-to-end without a real
   * `claude` binary. Three seams are exposed:
   *
   *  - `channelStore`: replaces the default `new ChannelStore()` so tests
   *    can drive a tmp-dir-backed store with seeded channels + tickets.
   *  - `repoAdminSpawner`: threaded into the `RepoAdminPool` so its per-
   *    admin children are fakes (no real CLI).
   *  - `workerSpawner`: replaces `new WorkerSpawner()` so the runner's
   *    spawn + monitor loop fires deterministically against a fake.
   *
   * All three are optional and ALL must be `undefined` in production.
   * Presence of any field constitutes a test invocation.
   */
  testOverrides?: {
    channelStore?: ChannelStore;
    repoAdminSpawner?: RepoAdminProcessSpawner;
    workerSpawner?: WorkerSpawner;
    /**
     * Override the pool's `~/.relay` base dir so the test's tmp dir is
     * used instead of the real home dir for session/admin logs. Also
     * used by {@link checkForStop} so the AL-9 kill-switch integration
     * test can drop a STOP file in the test's tmp dir.
     */
    rootDir?: string;
    /**
     * AL-6: replace the audit agent's LLM invoker with a deterministic
     * scripted function. Tests use this to return pre-shaped JSON so the
     * gating + decision-write path runs end-to-end without a real CLI
     * spawn. Production leaves this unset; `runPostCompletionAudit` is
     * never reached in pre-AL-4 shapes (the driver stub skips it) so the
     * production default is "no invoker, no audit" until AL-4 wires in a
     * factory-built agent.
     */
    auditInvoker?: AuditInvoker;
  };
  /**
   * AL-6 seam: invoked exactly once when the driver reaches "all
   * tickets done" — after the last ticket finishes draining and before
   * the lifecycle transitions to its terminal state. AL-4's real driver
   * is expected to populate this; until AL-4 ships, the default
   * behaviour (defined below) is to directly invoke
   * {@link runPostCompletionAudit} against the channel's ledger. Callers
   * that want to suppress the audit entirely can pass a no-op.
   *
   * The hook runs synchronously inside the loop's post-drain block: a
   * throw here is caught and warned, never rethrown, because the
   * autonomous loop's shutdown path must be robust to third-party
   * failures.
   */
  onAllTicketsComplete?: (ctx: AllTicketsCompleteContext) => Promise<void>;
}

/**
 * Context handed to the {@link StartAutonomousSessionOptions.onAllTicketsComplete}
 * seam. Everything the seam needs to run AL-6's
 * {@link runPostCompletionAudit} is on this object; no "reach into the
 * loop's internals" required.
 */
export interface AllTicketsCompleteContext {
  channel: Channel;
  channelStore: ChannelStore;
  sessionId: string;
  tracker: TokenTracker;
  /**
   * Post-drain budget headroom percentage (0..100). Pre-computed so the
   * seam implementation doesn't have to care whether the tracker has
   * replayed its JSONL yet.
   */
  budgetHeadroomPct: number;
  /**
   * Audit invoker threaded through from `testOverrides.auditInvoker`, if
   * any. Production is `undefined` — AL-4's real driver is expected to
   * build one from the agent factory.
   */
  auditInvoker?: AuditInvoker;
}

/**
 * Autonomous-loop driver entrypoint. The behaviour is gated by two env
 * flags so AL-12's pool lifecycle and AL-14's worker drain can be rolled
 * out independently:
 *
 *   1. When {@link RELAY_REPO_ADMIN_POOL_ENABLED} is off:
 *      Preserves the pre-AL-12 behaviour — no pool, no routing, lifecycle
 *      transitions to `killed` with reason `"al-13-pending"`. This is the
 *      safe default.
 *   2. When only the pool flag is on:
 *      Boots the repo-admin pool (AL-12) and routes each ready ticket
 *      through {@link TicketRouter} (AL-13) so the matching admin queues
 *      it. Workers are NOT spawned and queues are NOT drained — the
 *      lifecycle transitions to `killed` with reason `"al-14-pending"`.
 *      This mode exercises boot + routing in production without leaking
 *      worktrees.
 *   3. When BOTH {@link RELAY_REPO_ADMIN_POOL_ENABLED} and
 *      {@link RELAY_AL14_WORKER_DRAIN} are on:
 *      Full AL-14 behaviour. For each admin whose session is live
 *      (`state === "ready"`), drain its pending queue via
 *      {@link TicketRunner} — spawn a worker in a per-ticket worktree,
 *      monitor until the worker exits, and mark the ticket `verifying`
 *      (PR opened) / `failed` (AC4) on the board. Serialized inside each
 *      admin; parallel across admins. On completion the lifecycle
 *      transitions to `killed` with reason `"al-16-pending"`.
 *   4. Tears down pool + lifecycle + tracker. Errors during teardown are
 *      logged and swallowed: a cosmetic shutdown failure must not turn a
 *      successful handoff into a non-zero CLI exit.
 *
 * ## Why two flags
 *
 * AL-14 owns spawn + drain but NOT PR-merge cleanup (AL-4's scope). A
 * ticket whose worker opens a PR transitions to `awaiting-merge` and its
 * worktree persists on disk until a merge event reaches
 * {@link TicketRunner.handlePrMerged}. Until AL-4 ships merge-detection
 * wiring, every pool-enabled autonomous run with the drain on leaks one
 * worktree per successful ticket. Gating the drain behind its own flag
 * lets operators opt into that leak knowingly — and keeps a clean opt-
 * out path for AL-12/AL-13 exercise runs that shouldn't spawn workers at
 * all.
 *
 * PR-merge cleanup (AC3) is NOT driven here — the runner exposes
 * {@link TicketRunner.handlePrMerged}; the autonomous-loop's steady-
 * state driver (AL-4) will plumb PR-poller merge events into that hook
 * once the loop runs long enough to observe them. AL-14's single-pass
 * autonomous stub intentionally exits before any PR can merge, so the
 * hook is dormant here.
 */
export async function startAutonomousSession(opts: StartAutonomousSessionOptions): Promise<void> {
  const { sessionId, lifecycle, tracker, channel, allowedRepos, testOverrides } = opts;
  const stopPollIntervalMs = opts.stopPollIntervalMs ?? DEFAULT_STOP_POLL_INTERVAL_MS;

  // AL-9: transient flag so teardown can branch on whether we're
  // unwinding because of a user stop signal vs. normal terminal. The
  // lifecycle transition is the source of truth for downstream readers;
  // this flag only helps the local teardown log message.
  let userStopped = false;

  /**
   * AL-9 — poll the STOP file for this session. When the file is
   * present, transition the lifecycle to `winding_down` (if we're in
   * `dispatching`) with reason `"user-stop-signal"`. The transition is
   * idempotent — calling this helper again after the first signal is
   * observed is a no-op. Errors from the filesystem stat are logged
   * but NOT fatal: a flaky `~/.relay` shouldn't force-kill an
   * in-progress session, the wall-clock watchdog + token budget are
   * the hard stops. The STOP file is an advisory soft stop.
   */
  async function pollForStopAndWindDown(): Promise<boolean> {
    if (userStopped) return true;
    let present = false;
    try {
      present = await checkForStop(sessionId, testOverrides?.rootDir);
    } catch (err) {
      console.warn(
        `[autonomous-loop] STOP-file check failed for session ${sessionId}: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
      return false;
    }
    if (!present) return false;
    userStopped = true;
    const state = lifecycle.state;
    // Only `dispatching` has an edge to `winding_down`. From `planning`
    // we short-circuit to `killed` — we never started dispatching so
    // the wind-down drain has nothing to do. From `winding_down` /
    // `audit` we leave the state alone; the kill switch already fired
    // or a later transition has taken over.
    if (state === "dispatching") {
      try {
        await lifecycle.transition("winding_down", STOP_FILE_REASON);
      } catch (err) {
        console.warn(
          `[autonomous-loop] failed to transition to winding_down on STOP for session ${sessionId}: ${
            err instanceof Error ? err.message : String(err)
          }`
        );
      }
    } else if (state === "planning") {
      try {
        await lifecycle.transition("killed", STOP_FILE_REASON);
      } catch (err) {
        console.warn(
          `[autonomous-loop] failed to transition to killed on STOP for session ${sessionId}: ${
            err instanceof Error ? err.message : String(err)
          }`
        );
      }
    }
    console.log(
      `[autonomous-loop] STOP file observed for session ${sessionId}; winding down gracefully (poll cadence ${stopPollIntervalMs}ms).`
    );
    return true;
  }

  // AL-12 built the repo-admin pool, but the admin-process handshake
  // protocol it relies on is AL-14's deliverable. Without that protocol
  // the default spawner's child exits in ms (no prompt, stdin closed)
  // and the pool flaps until the rapid-restart ceiling fires. Gate pool
  // construction behind RELAY_REPO_ADMIN_POOL_ENABLED so production
  // `rly run --autonomous` invocations keep the pre-AL-12 behaviour
  // (clean `killed / al-13-pending` exit) until AL-14 flips the flag.
  const poolEnabled = isRepoAdminPoolEnabled();
  // AL-14 spawn + drain is gated by a SEPARATE flag from the pool flag.
  // Until AL-4 ships merge-detection cleanup, every ticket that reaches
  // `awaiting-merge` leaves a worktree on disk — the two-flag split lets
  // operators opt into that leak explicitly rather than inheriting it
  // by flipping the pool flag. When the drain flag is off but the pool
  // flag is on, the loop still routes tickets (AL-13) but no workers
  // are spawned, and the lifecycle exits with reason `al-14-pending`.
  const drainEnabled = poolEnabled && isWorkerDrainEnabled();

  if (!poolEnabled) {
    console.log(
      `[autonomous-loop] dispatcher not yet implemented — ` +
        `Session ${sessionId} marked as killed with reason "al-13-pending".`
    );
  } else if (!drainEnabled) {
    console.log(
      `[autonomous-loop] repo-admin pool + router enabled; worker drain disabled ` +
        `(RELAY_AL14_WORKER_DRAIN unset) — Session ${sessionId} will route tickets and ` +
        `mark killed with reason "al-14-pending".`
    );
  } else {
    console.log(
      `[autonomous-loop] routing channel tickets + draining repo-admin queues — ` +
        `Session ${sessionId} will mark killed with reason "al-16-pending" once drained. ` +
        `worker drain enabled; tickets that reach awaiting-merge state will leave ` +
        `worktrees on disk until AL-4 lands merge-detection cleanup.`
    );
  }

  // AL-13/16: single channel store instance shared by the router, the
  // runner fleet, and the coordinator's decisions audit. Reusing one
  // instance avoids redundant on-disk state checks and keeps all
  // writes going through the same in-memory mirror.
  const channelStore = testOverrides?.channelStore ?? new ChannelStore();

  // AL-16: inter-admin coordination bus. Construct BEFORE the pool so
  // the pool can thread the reference into each session it spawns —
  // any in-process MCP handler built on a session's behalf then has
  // both coordinator and alias available at construction, which is
  // what `coordination_send` needs to route end-to-end. When the pool
  // is disabled (AL-13 pending path) the coordinator stays null; no
  // coordination is possible without admins to address anyway.
  //
  // The coordinator wraps a `pool` reference for alias-lookup on send;
  // we forward-declare a lazily-populated proxy that the pool writes
  // into after construction, so the ordering (coordinator-before-pool
  // for wiring, pool-before-use for routing) holds without a circular
  // constructor call. The proxy is a thin Pick<> view — the coordinator
  // only calls `getSession` / `listSessions` on it.
  let poolRef: RepoAdminPool | null = null;
  const poolView: Pick<RepoAdminPool, "getSession" | "listSessions"> = {
    getSession(alias: string) {
      return poolRef?.getSession(alias) ?? null;
    },
    listSessions() {
      return poolRef?.listSessions() ?? [];
    },
  };
  const coordinator = poolEnabled
    ? new Coordinator({
        pool: poolView,
        channelStore,
        channelId: channel.channelId,
      })
    : null;

  const pool = poolEnabled
    ? new RepoAdminPool({
        channel,
        allowedAliases: allowedRepos.map((r) => r.alias),
        fullAccess: channel.fullAccess ?? false,
        lifecycle,
        spawner: testOverrides?.repoAdminSpawner,
        rootDir: testOverrides?.rootDir,
        // AL-16: hand the shared bus to the pool so every session it
        // constructs receives the reference and can pass it into its
        // MCP handler at construction time.
        coordinator,
      })
    : null;
  poolRef = pool;

  if (pool) {
    try {
      await pool.start();
    } catch (err) {
      console.warn(
        `[autonomous-loop] repo-admin pool failed to boot: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // AL-7 integration anchor. When AL-5 (PR reviewer) and AL-6 (audit agent)
  // land their driver hooks, each of their ack-requiring outputs must be
  // threaded through `decide({trust: opts.trust, ...})` from
  // `src/approvals/trust-gate.ts`. Under `supervised` the decision writes
  // a pending record to `~/.relay/approvals/<sessionId>/queue.jsonl`;
  // under `god` with `RELAY_AL7_GOD_AUTOMERGE=1` it writes an auto-approved
  // record (tagged `autoApprovedBy: "god-mode"`) AND returns
  // `{kind: "execute", auditRecordId, record}` so the caller performs the
  // merge / ticket write directly while the audit trail is already on
  // disk. AL-7 itself only produces + consumes the queue file; AL-8 owns
  // the approve / reject CLI surface.
  //
  // Concrete instantiation hint for AL-5 / AL-6 implementers — construct
  // the queue once at the start of the driver loop and thread the same
  // instance into every `decide()` call:
  //
  //   import { ApprovalsQueue, decide } from "../approvals/index.js";
  //   import { getRelayDir } from "../cli/paths.js";
  //
  //   const approvalsQueue = opts.approvalsQueue
  //     ?? new ApprovalsQueue({ rootDir: getRelayDir() });
  //
  //   // at PR-review-complete:
  //   const outcome = await decide({
  //     sessionId,
  //     trust: opts.trust,
  //     queue: approvalsQueue,
  //     action: { kind: "merge-pr", payload: { prUrl, reviewSummary } },
  //   });
  //   if (outcome.kind === "execute") { /* perform the merge */ }
  //
  // The `opts.approvalsQueue` fallback exists so the AL-4 driver test can
  // inject a tmp-dir-backed queue without touching `~/.relay/`.
  //
  // TODO(AL-5): at PR-review-complete, call `decide({..., action: {kind:
  //   "merge-pr", payload: {prUrl, reviewSummary}}})` and branch on the
  //   return. Do NOT auto-merge under supervised.
  // TODO(AL-6): at audit-proposal time, call `decide({..., action: {kind:
  //   "create-ticket", payload: {title, body, channelId}}})` and branch.
  //   Do NOT auto-write the ticket under supervised.
  //
  // AL-9: one pre-routing poll. Catches the "operator dropped STOP
  // before the loop reached its first tick" case — if we went straight
  // into routing without checking, a session could queue work into the
  // pool even though the user had already hit the kill switch. The
  // per-ticket check below handles STOP arriving mid-routing.
  await pollForStopAndWindDown();

  // AL-13: drain the channel's ticket board through the router exactly
  // once. AL-14 adds a second pass (gated by RELAY_AL14_WORKER_DRAIN)
  // that drains each admin's queue via TicketRunner — spawn a worker
  // per ticket, wait for it to open a PR (or fail), then exit. The
  // autonomous-loop's steady-state driver (AL-4) will replace this
  // single-pass shape; AL-14 just proves the end-to-end plumbing.
  //
  // AL-9: the routing loop below treats each iteration as a "tick" —
  // we re-poll the STOP file between tickets so the switch is honored
  // within one iteration (≤ stopPollIntervalMs equivalent; file poll
  // is O(ms)). When AL-4 lands its real multi-pass driver it picks up
  // the same `checkForStop` call and applies it to its own tick cadence.
  let terminalReason: "al-13-pending" | "al-14-pending" | "al-16-pending" = "al-13-pending";
  if (pool) {
    terminalReason = drainEnabled ? "al-16-pending" : "al-14-pending";
    const runners: TicketRunner[] = [];
    // AL-9: background poller that runs for the lifetime of the drain
    // phase. Fires at `stopPollIntervalMs` cadence (default 20s) so a
    // STOP file that lands AFTER routing completes but BEFORE the
    // drain finishes still flips the lifecycle to `winding_down`.
    // The poller NEVER force-kills runners — graceful wind-down
    // respects in-flight workers per AL-9's spec. It only transitions
    // the lifecycle so downstream audit-after-kill logic sees the
    // right state when the drain eventually completes.
    let stopPollTimer: NodeJS.Timeout | null = null;
    const armStopPoll = (): void => {
      const tick = async (): Promise<void> => {
        await pollForStopAndWindDown();
        if (!userStopped) {
          stopPollTimer = setTimeout(tick, stopPollIntervalMs);
          // Don't keep the event loop alive just for the poll — the
          // drain's promise is the thing the caller awaits.
          const h = stopPollTimer as { unref?: () => void };
          if (h && typeof h.unref === "function") h.unref();
        }
      };
      stopPollTimer = setTimeout(tick, stopPollIntervalMs);
      const h = stopPollTimer as { unref?: () => void };
      if (h && typeof h.unref === "function") h.unref();
    };
    try {
      const router = new TicketRouter({ pool, channel, channelStore });
      const boardTickets = await channelStore.readChannelTickets(channel.channelId);
      for (const ticket of boardTickets) {
        if (ticket.status !== "ready") continue;
        if (ticket.source === "linear") continue; // Linear mirror is read-only.
        // AL-9: re-poll before each ticket so a STOP that lands
        // mid-routing halts further dispatch. The already-routed
        // tickets continue through the drain phase — that's the
        // "respect in-flight workers" half of the graceful
        // wind-down contract.
        if (await pollForStopAndWindDown()) break;
        try {
          const result = await router.route(ticket);
          if (result.kind === "unroutable") {
            console.warn(
              `[autonomous-loop] ticket ${ticket.ticketId} unroutable (${result.reason}); ` +
                `surfaced to channel board as blocked.`
            );
          }
        } catch (err) {
          console.warn(
            `[autonomous-loop] router threw on ticket ${ticket.ticketId}: ${
              err instanceof Error ? err.message : String(err)
            }`
          );
        }
      }

      if (drainEnabled) {
        // AL-9: arm the background STOP-file poll NOW that we're about
        // to enter drain. A STOP arriving during drain flips the
        // lifecycle to `winding_down`; runners aren't signalled (spec
        // says respect in-flight workers) but the post-drain audit
        // gate reads the lifecycle + ledger to decide whether to run
        // the audit agent, so we need the state flip to land.
        armStopPoll();
        // AL-14: drain each admin's pending queue in parallel. Each admin
        // serializes internally (one worker at a time in its repo); two
        // different admins DO run in parallel. The drain promise resolves
        // once every admin's queue is empty AND every in-flight worker has
        // exited.
        const spawner = testOverrides?.workerSpawner ?? new WorkerSpawner();
        // Filter to live admins only: `listSessions()` also returns admins
        // whose child has died / been terminally marked `stopped` by the
        // pool's rapid-restart ceiling. Dispatching into those sessions
        // is a programming error (they throw) and surfacing nothing is
        // the right behaviour — the router already wrote the blocked
        // status for the routing failure.
        const admins = pool.listSessions().filter((s) => s.state === "ready");
        for (const admin of admins) {
          const assignment = channel.repoAssignments?.find((a) => a.alias === admin.alias);
          if (!assignment) continue;
          runners.push(
            new TicketRunner({
              admin,
              repoAssignment: assignment,
              channel,
              channelStore,
              spawner,
            })
          );
        }
        await Promise.all(
          runners.map((r) =>
            r.drain().catch((err) => {
              console.warn(
                `[autonomous-loop] ticket runner drain failed: ${
                  err instanceof Error ? err.message : String(err)
                }`
              );
            })
          )
        );
      }
    } catch (err) {
      console.warn(
        `[autonomous-loop] ticket routing pass failed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    } finally {
      // AL-9: clear the background STOP poll before we move into the
      // stop-all-runners step. Any pending tick that hasn't fired yet
      // is dropped — we're already on the teardown path, a late
      // lifecycle transition from the poll would race against the
      // explicit `killed` transition below and throw.
      if (stopPollTimer !== null) {
        clearTimeout(stopPollTimer);
        stopPollTimer = null;
      }
      // Ensure any in-flight worker is signalled before we unwind. Safe
      // to call even if drain() already finished — stop() is idempotent
      // and only hits still-running workers.
      await Promise.all(
        runners.map((r) =>
          r.stop("autonomous-loop-exit").catch((err) => {
            console.warn(
              `[autonomous-loop] runner stop failed: ${
                err instanceof Error ? err.message : String(err)
              }`
            );
          })
        )
      );
    }

    // AL-6: post-completion audit hook. Fires exactly once per session,
    // in the window between "last ticket drained" and "terminal lifecycle
    // transition". Gated internally on budget headroom + ledger health
    // (see `runPostCompletionAudit`). The `onAllTicketsComplete` seam is
    // exposed so AL-4's richer driver — which knows about retries,
    // stop-on-failure flags, etc. — can decide when "all tickets done"
    // truly holds; the default implementation treats "drain finished"
    // as the signal, which is correct for the current AL-14 single-pass
    // shape.
    //
    // Only fires when the worker drain was enabled. In drain-disabled
    // mode no tickets actually ran (AL-13 pending), so auditing what
    // "just completed" is meaningless and would write stale proposals
    // from a stale board.
    if (drainEnabled) {
      const headroomPct = Math.max(0, 100 - tracker.pct);
      const auditCtx: AllTicketsCompleteContext = {
        channel,
        channelStore,
        sessionId,
        tracker,
        budgetHeadroomPct: headroomPct,
        auditInvoker: testOverrides?.auditInvoker,
      };
      try {
        if (opts.onAllTicketsComplete) {
          await opts.onAllTicketsComplete(auditCtx);
        } else {
          await defaultOnAllTicketsComplete(auditCtx);
        }
      } catch (err) {
        // A misbehaving hook must NOT keep the loop from tearing down
        // its pool / lifecycle / tracker. Warn and continue.
        console.warn(
          `[autonomous-loop] onAllTicketsComplete hook failed: ${
            err instanceof Error ? err.message : String(err)
          }`
        );
      }
    }
  }

  // Only transition if we're still in a non-terminal state. A concurrent
  // threshold crossing or watchdog fire could theoretically have already
  // pushed us to `killed`; respect that and skip the transition in that
  // case to avoid throwing a LifecycleTransitionError the caller would
  // have to catch.
  //
  // AL-9: when `userStopped` is set, we ran the drain while already in
  // `winding_down`. The final transition is still `killed`, but the
  // reason carries the user-stop signal so log consumers + the post-
  // completion audit gate (see below) can distinguish a user-initiated
  // stop from a natural terminal.
  const state = lifecycle.state;
  const finalReason = userStopped ? STOP_FILE_REASON : terminalReason;
  try {
    if (state !== "killed" && state !== "done") {
      try {
        await lifecycle.transition("killed", finalReason);
      } catch (err) {
        console.warn(
          `[autonomous-loop] failed to transition lifecycle to killed: ${
            err instanceof Error ? err.message : String(err)
          }`
        );
      }
    }
  } finally {
    // AL-9: clear the STOP file after terminal transition so a subsequent
    // `rly run --autonomous` against the same sessionId doesn't immediately
    // kill from a leftover STOP file. Defensive — swallow errors since a
    // leftover STOP file is a minor correctness issue, never a reason to
    // fail teardown.
    try {
      await clearStopFile(sessionId, testOverrides?.rootDir);
    } catch (err) {
      console.warn(
        `[autonomous-loop] clearStopFile failed for session ${sessionId}: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // AL-9: post-completion audit gate. When the session is terminating
  // cleanly (or via user-stop after a fully-green routing pass), we
  // should run the AL-6 audit agent. The spec: "Killed session still
  // runs post-completion audit IF ledger was all-green before kill;
  // otherwise skips audit."
  //
  // AL-6 is not yet merged into this branch, so the implementation
  // here is intentionally a no-op with a structured log line. When
  // AL-6 lands, the `runAudit()` call slots in where the log lives —
  // the gating logic (ledger inspection, user-stop tolerance) is the
  // piece AL-9 owns and ships now.
  try {
    await maybeRunAuditHook({
      sessionId,
      channel,
      channelStore,
      userStopped,
      lifecycle,
    });
  } catch (err) {
    console.warn(
      `[autonomous-loop] audit gate check failed: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }

  // AL-16: close the coordinator BEFORE stopping the pool. Order
  // matters — once `pool.stop()` starts, each session unwinds and
  // `getSession(to)` begins returning null, so a late-arriving
  // `coordination_send` would resolve with `no-such-admin` (generic,
  // confusing post-mortem) instead of the cleaner `coordinator-closed`
  // the close path produces. Closing first guarantees the in-flight
  // race resolves on the close rail.
  if (coordinator) {
    try {
      await coordinator.close();
    } catch (err) {
      console.warn(
        `[autonomous-loop] coordinator close failed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // Terminal lifecycle transition triggers the pool's auto-stop, but also
  // await it here so teardown happens before the CLI returns.
  if (pool) {
    try {
      await pool.stop();
    } catch (err) {
      console.warn(
        `[autonomous-loop] repo-admin pool stop failed: ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }

  // Close out resources. Any in-flight writes drain here; errors are
  // warned but never thrown — the CLI exit path is the wrong place to
  // surface a teardown failure.
  try {
    await lifecycle.close();
  } catch (err) {
    console.warn(
      `[autonomous-loop] lifecycle close failed: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
  }
  try {
    await tracker.close();
  } catch (err) {
    console.warn(
      `[autonomous-loop] tracker close failed: ${err instanceof Error ? err.message : String(err)}`
    );
  }
}

/**
 * AL-6: default implementation of the `onAllTicketsComplete` seam.
 * Reads the channel's current ticket ledger + decisions, then hands them
 * to {@link runPostCompletionAudit}. Logs the outcome so an operator can
 * tell from the autonomous-loop's final output whether the audit fired,
 * was gated off, or produced an invalid response.
 *
 * Auto-audit is disabled when no `auditInvoker` is supplied — i.e. the
 * production default until AL-4 wires the agent factory into this seam.
 * Tests explicitly pass an invoker via `testOverrides.auditInvoker`.
 */
async function defaultOnAllTicketsComplete(ctx: AllTicketsCompleteContext): Promise<void> {
  if (!ctx.auditInvoker) {
    // No invoker, no audit. Keeping this silent by default — the
    // autonomous-loop's pre-audit log already told the operator that
    // AL-4 is not yet wired; shouting "audit skipped (no invoker)" on
    // every successful run would just add noise.
    return;
  }

  const tickets = await ctx.channelStore.readChannelTickets(ctx.channel.channelId);
  const decisions = await ctx.channelStore.listDecisions(ctx.channel.channelId);

  const result: AuditRunResult = await runPostCompletionAudit({
    channel: ctx.channel,
    channelStore: ctx.channelStore,
    run: {
      sessionId: ctx.sessionId,
      tickets,
      decisions,
      // Recent git log capture is deferred to AL-4's richer driver,
      // which knows which repos the run touched. The audit prompt
      // tolerates an empty array, so skipping here produces no noise.
      recentCommits: [],
    },
    budgetHeadroomPct: ctx.budgetHeadroomPct,
    invokeAudit: ctx.auditInvoker,
  });

  if (result.kind === "fired") {
    console.log(
      `[autonomous-loop] audit-agent fired — ${result.proposalsWritten} proposal(s) written.`
    );
  } else if (result.kind === "skipped") {
    console.log(`[autonomous-loop] audit-agent skipped (${result.reason}).`);
  } else {
    console.warn(
      `[autonomous-loop] audit-agent returned invalid response (${result.issues.length} issue(s)).`
    );
  }
}

/**
 * AL-9's audit gate. AL-6 ships the actual audit agent; this helper
 * owns the gating logic and logs the decision so the AL-6 merge is a
 * drop-in call replacement (swap the `console.log` for the real
 * runAudit call). Separating gate from actuator keeps both tickets
 * independently verifiable.
 *
 * ## Gate
 *
 * The spec (AL-9 AC3): "Killed session still runs the post-completion
 * audit IF the ledger was all-green before the kill; otherwise skips
 * audit." The interpretation:
 *
 *   - "all-green" = every ticket on the channel's board ended in
 *     `completed` (or was never picked up, i.e. still `pending` /
 *     `blocked` — those aren't failures, just unreached work).
 *   - Any `failed` / `retry` / `executing` / `verifying` ticket means
 *     the ledger wasn't green; skip audit because auditing a partial
 *     run would produce a misleading report.
 *
 * Natural terminal (no user stop, no threshold kill) follows the same
 * rule — if the routing pass finished cleanly and every ticket is
 * completed, audit; otherwise skip.
 */
async function maybeRunAuditHook(args: {
  sessionId: string;
  channel: Channel;
  channelStore: ChannelStore;
  userStopped: boolean;
  lifecycle: SessionLifecycle;
}): Promise<void> {
  const { sessionId, channel, channelStore, userStopped } = args;

  const tickets = await channelStore.readChannelTickets(channel.channelId);
  // "green" means: no ticket ended in an unhealthy terminal / partial
  // state. A completely empty board is vacuously green (the audit on
  // an empty session is trivially "nothing to report"); AL-6 decides
  // whether to short-circuit in that case.
  const unhealthy = tickets.filter(
    (t) =>
      t.status === "failed" ||
      t.status === "retry" ||
      t.status === "executing" ||
      t.status === "verifying"
  );
  const allGreen = unhealthy.length === 0;

  if (!allGreen) {
    console.log(
      `[autonomous-loop] skipping post-completion audit for session ${sessionId} — ` +
        `ledger has ${unhealthy.length} non-green ticket(s) ` +
        `(${unhealthy
          .slice(0, 3)
          .map((t) => `${t.ticketId}:${t.status}`)
          .join(", ")}${unhealthy.length > 3 ? ", …" : ""}).`
    );
    return;
  }

  // Green — audit would run. AL-6 slots its runAudit() here. The log
  // line is the marker the audit gate fires; AL-9's tests key on it.
  const trigger = userStopped ? "user-stop-signal" : "natural-terminal";
  console.log(
    `[autonomous-loop] post-completion audit eligible for session ${sessionId} ` +
      `(trigger=${trigger}, ticketsGreen=${tickets.length}); AL-6 hook not yet wired.`
  );
}
